package com.nc.finlocknc.feature.CreateLoan.model.request

data class AddCustomerRequest(
    val name: String,
    val email: String,
    val contact: String,
   // val pan: String,
   // val aadhar: String,
    val guaranator_name: String,
    val guaranator_mobile: String,
    val product_amount: String,
    val no_of_emi: Int,
    //val financer_bank: String,
    val down_payment: String,
    val balance_amount: String,
    val emi_amount: String,
    val interest_rate: String,
    val net_amount: String,
    val description: String,
    val mobile_brand: String,
    val mobile_model: String,
    val device_type: String,
    val devicename: String,
    val imei: String,
    val imeiII: String,
    val device_id: String,
    val license_key: String,
    val status: String,
    val mobile_status: Int,
    val pan_file: String,
    val customer_profile_pic : String,
    val aadhar_file: String,
    val consent_file: String,
    val customer_sign: String,
    val retailer_key: Int
)
